version: "2"
services:
  web:
    container_name: laravel-redis-docker-nginx-latest
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./laravel-redis:/var/www
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
      - mysql
      - redis
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: laravel-redis-docker-php-fpm
    image: devilbox/php-fpm:7.4-prod-0.106
    restart: always
    volumes:
      - ./laravel-redis:/var/www
      - ./php/php.ini:/etc/php/7.4/fpm/php.ini
    links:
      - mysql
  mysql:
    container_name: laravel-redis-docker-mysql
    image: mysql:5.6.26
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=123456
  redis:
    container_name: laravel-redis-docker-redis
    restart: always
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
